---

- hosts: localhost
  tasks:
    - name: Add target to in-memory inventory
      add_host:
        name: "{{ public_ip }}"
        groups: target_node
        ansible_user: "{{ ssh_user | default('root') }}"
        ansible_ssh_port: "{{ ssh_port | default(22) }}"

- name: Add node to admin panel
  hosts: localhost
  tasks:
    - name: Create node directory
      file:
        path: "{{ nebula_control_dir }}/hosts/{{ node_name }}"
        state: directory

    - name: Sign certificates
      command: nebula-cert sign -ca-key "{{ nebula_control_dir }}/ca/ca.key" --ca-crt "{{ nebula_control_dir }}/ca/ca.crt" -out-key "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.key" -out-crt "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.crt" -name "{{ node_name }}" -ip "{{ nebula_ip }}/16" -groups "{{ groups }}"

    - name: Generate client config with lighthouse hosts
      copy:
        src: "{{ node_config }}"
        dest: "{{ nebula_control_dir }}/hosts/{{ node_name }}/config.yml"


- name: Set up target node
  hosts: target_node
  vars:
    enable_ufw: "{{ ufw | default(true) }}"
    enable_docker_ufw: "{{ docker_ufw | default(false) }}"
  tasks:
    - name: Install nebula binaries
      unarchive:
        src: https://github.com/slackhq/nebula/releases/download/v1.6.0/nebula-linux-amd64.tar.gz
        dest: /usr/bin
        mode: 0755
        remote_src: yes

    - name: Create nebula config directory
      file:
        path: /etc/nebula
        state: directory
        mode: 0755

    - name: Push configs to node
      synchronize: 
        src: "{{ nebula_control_dir }}/hosts/{{ node_name }}/"
        dest: "/etc/nebula/"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost

    - name: Push certs to node
      synchronize: 
        src: "{{ nebula_control_dir }}/ca/ca.crt"
        dest: "/etc/nebula"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost

    - name: Push service config to node
      synchronize: 
        src: "{{ nebula_control_dir }}/defaults/nebula.service"
        dest: "/etc/systemd/system"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost

    - name: Enable and start nebula service
      systemd:
        name: nebula
        enabled: true
        state: started

    - name: Configure UFW rules
      command: "{{ item }}"
      with_items:
        - "ufw allow 4242/udp"
        - "ufw allow 22/tcp"
        - "ufw allow {{ ssh_port }}/tcp"
        - "ufw allow in on nebula1"
        - "ufw --force enable"
        - "ufw reload"
      when: enable_ufw | bool

    - name: Enable UFW
      systemd:
        name: ufw
        enabled: true
        state: started
      when: enable_ufw | bool

    - name: Fetch Docker UFW rules
      synchronize: 
        src: "{{ nebula_control_dir }}/defaults/docker-ufw.rules"
        dest: "/tmp"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost
      when: enable_docker_ufw | bool

    - name: Configure Docker UFW rules (TODO -- investigate potential idempotency issues due to cat)
      shell: "{{ item }}"
      with_items:
        - "cat /tmp/docker-ufw.rules >> /etc/ufw/after.rules"
        - "ufw reload"
      when: enable_docker_ufw | bool
