---

- hosts: localhost
  tasks:
    - name: Add target node to in-memory inventory
      add_host:
        name: "{{ public_ip }}"
        groups: target_nodes
        ansible_user: "{{ ssh_user | default('root') }}"
        ansible_ssh_port: "{{ ssh_port | default('22') }}"

- name: Add node to admin panel
  hosts: localhost
  vars:
    nebula_dir: /home/nebula/nebula
    ip_list: /home/nebula/nebula/store/ip_list.yml
  tasks:
    - name: Create node directory
      file:
        path: "{{ nebula_dir }}/hosts/{{ node_name }}"
        state: directory

    - name: Sign certificates
      command: nebula-cert sign -ca-key "{{ nebula_dir }}/ca/ca.key" --ca-crt "{{ nebula_dir }}/ca/ca.crt" -out-key "{{ nebula_dir }}/hosts/{{ node_name }}/host.key" -out-crt "{{ nebula_dir }}/hosts/{{ node_name }}/host.crt" -name "{{ node_name }}" -ip "{{ nebula_ip }}/16" -groups "{{ groups }}"

    - name: Create node config
      copy: src="{{ nebula_dir }}/defaults/client.yml" dest="{{ nebula_dir }}/hosts/{{ node_name }}/config.yml"

    - include_vars: "{{ ip_list }}"

    - name: Edit node config with lighthouse hosts
      command: yq -i '
                with(.static_host_map["{{ item }}"]; . = ["{{ lighthouses[item] }}"] | . style="flow") |
                .lighthouse.hosts += ["{{ item }}"]
              ' "{{ nebula_dir }}/hosts/{{ node_name }}/config.yml"
      with_items: "{{ lighthouses }}"

    - name: Add node IP to used IP list on successful config generation
      command: yq -i '.clients["{{ nebula_ip }}"] = "{{ public_ip }}"' "{{ ip_list }}"

- name: Set up target node
  hosts: target_nodes
  vars:
    nebula_dir: /home/nebula/nebula
    enable_ufw: "{{ ufw | default(true) }}"
    enable_docker_ufw: "{{ docker_ufw | default(false) }}"
    # dns_resolved: "{{ dns_resolved | default(false) }}"
  tasks:
    - name: Install nebula binaries
      unarchive:
        src: https://github.com/slackhq/nebula/releases/download/v1.6.0/nebula-linux-amd64.tar.gz
        dest: /usr/bin
        mode: 0755
        remote_src: yes

    - name: Create nebula config directory
      file:
        path: /etc/nebula
        state: directory
        mode: 0755

    - name: Push configs to node
      synchronize: 
        src: "{{ nebula_dir }}/hosts/{{ node_name }}/"
        dest: "/etc/nebula/"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost

    - name: Push certs to node
      synchronize: 
        src: "{{ nebula_dir }}/ca/ca.crt"
        dest: "/etc/nebula"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost

    - name: Push service config to node
      synchronize: 
        src: "{{ nebula_dir }}/defaults/nebula.service"
        dest: "/etc/systemd/system"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost

    - name: Enable and start nebula service
      systemd:
        name: nebula
        enabled: true
        state: started

    - name: Configure UFW rules
      command: "{{ item }}"
      with_items:
        - "ufw allow 4242/udp"
        - "ufw allow 22/tcp"
        - "ufw allow {{ ssh_port }}/tcp"
        - "ufw allow in on nebula1"
        - "ufw --force enable"
        - "ufw reload"
      when: enable_ufw | bool

    - name: Enable UFW
      systemd:
        name: ufw
        enabled: true
        state: started
      when: enable_ufw | bool

    - name: Fetch Docker UFW rules
      synchronize: 
        src: "{{ nebula_dir }}/defaults/docker-ufw.rules"
        dest: "/tmp"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost
      when: enable_docker_ufw | bool

    - name: Configure Docker UFW rules (TODO -- idempotency issues due to cat?)
      shell: "{{ item }}"
      with_items:
        - "cat /tmp/docker-ufw.rules >> /etc/ufw/after.rules"
        - "ufw reload"
      when: enable_docker_ufw | bool

    # - name: Fetch existing IP list
    #   synchronize: 
    #     src: "{{ nebula_dir }}/hosts/ip_list.yml"
    #     dest: "/tmp/"
    #     dest_port: "{{ ssh_port }}"
    #     mode: push
    #   delegate_to: localhost
    #   when: dns_resolved | bool

    # - include_vars: "/tmp/ip_list.yml"
    # - name: Update DNS
    #   shell: sed -i -E "s/^.{0,1}(DNS=.*)/\1 {{ item }}:5353/" /etc/systemd/resolved.conf
    #   with_items: "{{ lighthouses }}"
    #   when: dns_resolved | bool

    # - name: Update domains
    #   shell: sed -i -E 's/^.{0,1}(Domains=.*)/\1 ~lgns/' /etc/systemd/resolved.conf
    #   when: dns_resolved | bool

    # - name: Reload DNS config
    #   systemd:
    #     name: systemd-resolved
    #     state: started
    #   when: dns_resolved | bool
