---

- name: Adding node to admin panel and zip configs
  hosts: localhost
  tasks:
    - name: Creating node directory
      file:
        path: "{{ nebula_control_dir }}/hosts/{{ node_name }}"
        state: directory

    - name: Signing certificates
      command: nebula-cert sign -ca-key "{{ nebula_control_dir }}/ca/ca.key" --ca-crt "{{ nebula_control_dir }}/ca/ca.crt" -out-key "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.key" -out-crt "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.crt" -name "{{ node_name }}" -ip "{{ nebula_ip }}/16" -groups "{{ nebula_groups }}"

    - name: Generating node config with lighthouse hosts
      copy:
        src: "{{ node_config }}"
        dest: "{{ nebula_control_dir }}/hosts/{{ node_name }}/config.yml"

    - name: Creating a zip of the configs
      archive:
        path: 
          - "{{ nebula_control_dir }}/hosts/{{ node_name }}/config.yml"
          - "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.crt"
          - "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.key"
          - "{{ nebula_control_dir }}/ca/ca.crt"
          - "{{ nebula_control_dir }}/defaults/nebula.service"
          - "{{ network_config }}"
        dest: "{{ nebula_control_dir }}/hosts/{{ node_name }}/config.zip"
        format: zip
