---

- name: Add node to admin panel and zip configs
  hosts: localhost
  tasks:
    - name: Create node directory
      file:
        path: "{{ nebula_control_dir }}/hosts/{{ node_name }}"
        state: directory

    - name: Sign certificates
      command: nebula-cert sign -ca-key "{{ nebula_control_dir }}/ca/ca.key" --ca-crt "{{ nebula_control_dir }}/ca/ca.crt" -out-key "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.key" -out-crt "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.crt" -name "{{ node_name }}" -ip "{{ nebula_ip }}/16" -groups "{{ groups }}"

    - name: Generate node config with lighthouse hosts
      copy:
        src: "{{ node_config }}"
        dest: "{{ nebula_control_dir }}/hosts/{{ node_name }}/config.yml"

    - name: Create a zip of the configs
      archive:
        path: 
          - "{{ nebula_control_dir }}/hosts/{{ node_name }}/config.yml"
          - "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.crt"
          - "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.key"
        dest: "{{ nebula_control_dir }}/hosts/{{ node_name }}/config.zip"
        format: zip
