---

- name: Setting up current node
  host: localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  become: yes
  become_user: root
  tasks:
    - name: Creating Nebula config directory
      file:
        path: /etc/nebula
        state: directory
        mode: 0755

    - name: Installing Nebula binaries
      unarchive:
        src: https://github.com/slackhq/nebula/releases/download/v1.6.0/nebula-linux-amd64.tar.gz
        dest: /usr/bin
        mode: 0755
        remote_src: yes

    - name: Unzipping configs
      unarchive:
        src: "{{ node_config }}"
        dest: /etc/nebula
      
    - name: Copying service config
      copy:
        src: /etc/nebula/nebula.service
        dest: /etc/systemd/system/nebula.service
      
    - name: Copying network config
      copy:
        src: /etc/nebula/nebula1.network
        dest: /etc/systemd/network/nebula1.network

    - name: Restarting systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted

    - name: Restarting systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted

    - name: Enabling and starting Nebula service
      systemd:
        name: nebula
        enabled: true
        state: started

    - name: Configuring UFW rules
      command: "{{ item }}"
      with_items:
        - "ufw allow 4242/udp"
        - "ufw allow {{ ssh_port }}/tcp"
        - "ufw allow in on nebula1"
        - "ufw --force enable"
        - "ufw reload"
      when: enable_ufw | bool

    - name: Enabling UFW
      systemd:
        name: ufw
        enabled: true
        state: started
      when: enable_ufw | bool

    - name: Cleaning up
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nebula/nebula.service
        - /etc/nebula/nebula1.network
