---

- name: Setting up current node
  hosts: localhost
  vars_prompt:
  - name: "ansible_become_pass"
    prompt: "[sudo] password"
    private: yes
  become: yes
  become_method: community.general.sudosu
  tasks:
    - name: Creating Nebula config directory
      file:
        path: /etc/nebula
        state: directory
        mode: 0755

    - name: Installing Nebula binaries
      unarchive:
        src: https://github.com/slackhq/nebula/releases/download/v1.6.0/nebula-linux-amd64.tar.gz
        dest: /usr/local/bin
        mode: 0755
        remote_src: yes

    - name: Unzipping configs
      shell: "unzip -P {{ archive_password }} {{ node_config }} -d /tmp/"
      # unarchive:
      #   src: "{{ node_config }}"
      #   dest: /tmp

    - name: Copying Nebula configs
      synchronize:
        src: /tmp/nebula/
        dest: /etc/nebula
      
    - name: Copying service config
      synchronize:
        src: /tmp/defaults/nebula.service
        dest: /etc/systemd/system/nebula.service
      
    - name: Copying network config
      synchronize:
        src: /tmp/defaults/nebula1.network
        dest: /etc/systemd/network/nebula1.network

    - name: Restarting systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted

    - name: Restarting systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted

    - name: Enabling and starting Nebula service
      systemd:
        name: nebula
        enabled: true
        state: started

    - name: Configuring UFW rules
      command: "{{ item }}"
      with_items:
        - "ufw allow 4242/udp"
        - "ufw allow in on nebula1"
        - "ufw reload"

    - name: Cleaning up
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/nebula
        - /tmp/defaults
