---

- hosts: localhost
  tasks:
    - name: Adding target to in-memory inventory
      add_host:
        name: "{{ nebula_ip }}"
        groups: target_node
        ansible_user: "{{ ssh_user | default('root') }}"
        ansible_ssh_port: "{{ ssh_port | default(22) }}"
      when: nebula_ip


- name: Syncing configs and restart Nebula service on the target node if remotely managed
  hosts: target_node
  vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "[sudo] password"
    private: yes
  become: yes
  become_method: community.general.sudosu
  tasks:
    - name: Pushing configs to node
      copy:
        src: "{{ nebula_control_dir }}/hosts/{{ node_name }}/"
        dest: "/etc/nebula/"

    - name: Restarting Nebula service
      shell: kill -HUP $(pidof nebula)
