---

- hosts: localhost
  tasks:
    - name: Adding target node to in-memory inventory
      add_host:
        name: "{{ public_ip }}"
        groups: target_nodes
        ansible_user: "{{ ssh_user | default('root') }}"
        ansible_ssh_port: "{{ ssh_port | default('22') }}"
      when: public_ip

- name: Removing node from admin panel
  hosts: localhost
  tasks:
    - name: Deleting node directory
      file:
        path: "{{ nebula_control_dir }}/hosts/{{ node_name }}"
        state: absent
      ignore_errors: yes

- name: Undoing changes on the target node
  hosts: target_nodes
  vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "[sudo] password"
    private: yes
  become: yes
  become_method: community.general.sudosu
  tasks:
    - name: Disabling and stop Nebula service
      systemd:
        name: nebula
        enabled: false
        state: stopped
      ignore_errors: yes

    - name: Deleting config directory
      file:
        path: /etc/nebula
        state: absent
      ignore_errors: yes

    - name: Deleting network config
      file:
        path: /etc/systemd/network/nebula1.network
        state: absent
      ignore_errors: yes

    - name: Restarting systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
      ignore_errors: yes

    - name: Restarting systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted
      ignore_errors: yes

    - name: Deleting Nebula binaries
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      with_items:
        - nebula
        - nebula-cert
      ignore_errors: yes

    - name: Deleting Nebula service files
      file:
        path: /etc/systemd/system/nebula.service
        state: absent
      ignore_errors: yes

    - name: Resetting UFW rules
      ufw:
        state: reset
      ignore_errors: yes
