---

- hosts: localhost
  tasks:
    - name: Adding target to in-memory inventory
      add_host:
        name: "{{ public_ip }}"
        groups: target_node
        ansible_user: "{{ ssh_user | default('root') }}"
        ansible_ssh_port: "{{ ssh_port | default(22) }}"

- name: Adding node to admin panel
  hosts: localhost
  tasks:
    - name: Removing existing certificates
      file:
        path: "{{ nebula_control_dir }}/hosts/{{ node_name }}/{{ item }}"
        state: absent
      with_items:
        - ca
        - host.crt
        - host.key

    - name: Signing certificates
      command: nebula-cert sign -ca-key "{{ nebula_control_dir }}/ca/ca.key" --ca-crt "{{ nebula_control_dir }}/ca/ca.crt" -out-key "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.key" -out-crt "{{ nebula_control_dir }}/hosts/{{ node_name }}/host.crt" -name "{{ node_name }}" -ip "{{ nebula_ip }}/16" -groups "{{ nebula_groups }}"

- name: Setting up target node
  hosts: target_node
  tasks:
    - name: Pushing Nebula configs to node
      synchronize: 
        src: "{{ nebula_control_dir }}/hosts/{{ node_name }}/"
        dest: "/etc/nebula/"
        dest_port: "{{ ssh_port }}"
        mode: push
      delegate_to: localhost

    - name: Restarting Nebula service
      systemd:
        name: nebula
        state: restarted
